# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class N2xCli < Formula
  desc "n2x-cli"
  homepage "https://n2x.io"
  version "0.0.4"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/n2x-io/x-cli/releases/download/v0.0.4/n2x-cli_0.0.4_darwin_amd64.tar.gz"
      sha256 "12189035116fad42cb94073b6e48cd51d60360b9722d86ad3384089acf664ab8"

      def install
        bin.install "n2xctl"
        bash_completion.install "completions/n2xctl.bash" => "n2xctl"
        zsh_completion.install "completions/n2xctl.zsh" => "_n2xctl"
        fish_completion.install "completions/n2xctl.fish"
      end
    end
    on_arm do
      url "https://github.com/n2x-io/x-cli/releases/download/v0.0.4/n2x-cli_0.0.4_darwin_arm64.tar.gz"
      sha256 "ecfbb2514f71cca1ff84d00e6228e560231e751c7f0df73ca2ab1f79751ce469"

      def install
        bin.install "n2xctl"
        bash_completion.install "completions/n2xctl.bash" => "n2xctl"
        zsh_completion.install "completions/n2xctl.zsh" => "_n2xctl"
        fish_completion.install "completions/n2xctl.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/n2x-io/x-cli/releases/download/v0.0.4/n2x-cli_0.0.4_linux_amd64.tar.gz"
        sha256 "63de69d03eee09da0eb4006af3df787072544ce0839d8b1f02b8dbd6a23703b7"

        def install
          bin.install "n2xctl"
          bash_completion.install "completions/n2xctl.bash" => "n2xctl"
          zsh_completion.install "completions/n2xctl.zsh" => "_n2xctl"
          fish_completion.install "completions/n2xctl.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/n2x-io/x-cli/releases/download/v0.0.4/n2x-cli_0.0.4_linux_arm64.tar.gz"
        sha256 "323ad23b934a85636e3ad9eda3b2935f541867e22c4c2a8debd56c94b6689898"

        def install
          bin.install "n2xctl"
          bash_completion.install "completions/n2xctl.bash" => "n2xctl"
          zsh_completion.install "completions/n2xctl.zsh" => "_n2xctl"
          fish_completion.install "completions/n2xctl.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/n2xctl version show"
  end
end
