# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class N2xCli < Formula
  desc "n2x-cli"
  homepage "https://n2x.io"
  version "0.0.1"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/n2x-io/x-cli/releases/download/v0.0.1/n2x-cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "5474e02367cfb7b42eb741989729c5b8558af1d6568aa7625e41125c94f5be47"

      def install
        bin.install "n2xctl"
        bash_completion.install "completions/n2xctl.bash" => "n2xctl"
        zsh_completion.install "completions/n2xctl.zsh" => "_n2xctl"
        fish_completion.install "completions/n2xctl.fish"
      end
    end
    on_arm do
      url "https://github.com/n2x-io/x-cli/releases/download/v0.0.1/n2x-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "8cee2f5ad94911f0a0ae0d94f1d28f9d0b5a457d201ac07e883dd095d21ac3f0"

      def install
        bin.install "n2xctl"
        bash_completion.install "completions/n2xctl.bash" => "n2xctl"
        zsh_completion.install "completions/n2xctl.zsh" => "_n2xctl"
        fish_completion.install "completions/n2xctl.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/n2x-io/x-cli/releases/download/v0.0.1/n2x-cli_0.0.1_linux_amd64.tar.gz"
        sha256 "694d9f41b3dd03ce74abcd6579a8a24b3cc4608a75b18894e7dfcf079e57bb1e"

        def install
          bin.install "n2xctl"
          bash_completion.install "completions/n2xctl.bash" => "n2xctl"
          zsh_completion.install "completions/n2xctl.zsh" => "_n2xctl"
          fish_completion.install "completions/n2xctl.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/n2x-io/x-cli/releases/download/v0.0.1/n2x-cli_0.0.1_linux_arm64.tar.gz"
        sha256 "a9daaf1f9f7085b48bc40b7a753b4713bf484f3dcf0b9b4a84dce2fb18716b6b"

        def install
          bin.install "n2xctl"
          bash_completion.install "completions/n2xctl.bash" => "n2xctl"
          zsh_completion.install "completions/n2xctl.zsh" => "_n2xctl"
          fish_completion.install "completions/n2xctl.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/n2xctl version show"
  end
end
