# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class N2xCli < Formula
  desc "n2x-cli"
  homepage "https://n2x.io"
  version "0.0.3"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/n2x-io/x-cli/releases/download/v0.0.3/n2x-cli_0.0.3_darwin_amd64.tar.gz"
      sha256 "7a13d496fbb5cd04209606400b94eb9238f649575e8eb6a75ef1707275e36795"

      def install
        bin.install "n2xctl"
        bash_completion.install "completions/n2xctl.bash" => "n2xctl"
        zsh_completion.install "completions/n2xctl.zsh" => "_n2xctl"
        fish_completion.install "completions/n2xctl.fish"
      end
    end
    on_arm do
      url "https://github.com/n2x-io/x-cli/releases/download/v0.0.3/n2x-cli_0.0.3_darwin_arm64.tar.gz"
      sha256 "9705664c9425b9219d8fc63d1d5e81e7a64b86d97b0a520e8a3ef5f5a362e6b3"

      def install
        bin.install "n2xctl"
        bash_completion.install "completions/n2xctl.bash" => "n2xctl"
        zsh_completion.install "completions/n2xctl.zsh" => "_n2xctl"
        fish_completion.install "completions/n2xctl.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/n2x-io/x-cli/releases/download/v0.0.3/n2x-cli_0.0.3_linux_amd64.tar.gz"
        sha256 "94c21017644ef4a1840201369813e225499fe1e35baccf0dcd69c9c69334688b"

        def install
          bin.install "n2xctl"
          bash_completion.install "completions/n2xctl.bash" => "n2xctl"
          zsh_completion.install "completions/n2xctl.zsh" => "_n2xctl"
          fish_completion.install "completions/n2xctl.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/n2x-io/x-cli/releases/download/v0.0.3/n2x-cli_0.0.3_linux_arm64.tar.gz"
        sha256 "801660418cc92668d3bc7fabdd8592e8de4a307446792b59c523f5dc2e1f7ab3"

        def install
          bin.install "n2xctl"
          bash_completion.install "completions/n2xctl.bash" => "n2xctl"
          zsh_completion.install "completions/n2xctl.zsh" => "_n2xctl"
          fish_completion.install "completions/n2xctl.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/n2xctl version show"
  end
end
